- name: Create /root/.ssh
  file: path=/root/.ssh state=directory

- name: Install SSH keys
  lineinfile: line={{ item }} dest=/root/.ssh/authorized_keys create=yes
  with_items:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILCNH6UlkkHxR815mjbHBJTomrnaFHCjiG6760MELRFj finn@wash
