- name: Update and upgrade
  apt: update_cache=yes upgrade=dist

- name: Install depends
  apt: name={{ item }} state=present
  with_items: [python-pip, python-dev, libssl-dev, libffi-dev]

- name: Install ansible
  pip: name=ansible state=latest

- name: Make /etc/ansible/facts.d/pull.fact
  template:
    src: pull.fact
    dest: /etc/ansible/facts.d/pull.fact

- name: Install the ansible-pull script
  template: src=ansible-pull.sh dest=/usr/sbin/run-ansible-pull mode=0755 owner=root group=root

- name: Install cronjob
  cron: name="Ansible Pull" minute="{{ ansible_local.pull.minute | default(59 | random) }}" job="/usr/sbin/run-ansible-pull"
