- name: Update and upgrade
  apt: update_cache=yes upgrade=dist

- name: Install depends
  apt: name={{ item }} state=present
  with_items: [virtualenv, python-dev, libssl-dev, libffi-dev, netcat]

- name: Make /etc/ansible/facts.d
  file: path=/etc/ansible/facts.d state=directory recurse=yes

- name: Install the ansible-pull script
  template: src=ansible-pull.sh dest=/usr/sbin/run-ansible-pull mode=0755 owner=root group=root

- name: Install ansible depends
  pip:
    name: "{{ item }}"
    virtualenv: /var/ansible
  with_items: [apt]

- name: Install cronjob
  cron: name="Ansible Pull" minute="0" job="/usr/sbin/run-ansible-pull"
